name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install Packages
      run: sudo apt update -y ; sudo apt -y install qt5-qmake
    - name: qmake-qt5
      run: qmake-qt5
    - name: make
      run: make
